### ISSUE TITLE
Running the Server on AWS

### ISSUE THREAD

**Issue by agoz17** [bounswe/bounswe2017group7#105]
We can't run the django server on our AWS instance. We can share the links and ideas we find to help us to resolve this issue. Anyone wants to contribute can assign the problem himself/herself.

**Comment by agoz17** [comment]
I think we have a problem that is similar on this link: https://stackoverflow.com/questions/19921705/how-do-i-access-my-django-app-running-on-amazon-ec2

**Comment by sevdacopur** [comment]
Changing the security group settings might be a solution.

**Comment by melihmutlu** [comment]
It's now running. Thanks to @sevdacopur

**Comment by agoz17** [comment]
It is solved by Sevda via changing port settings. Thank you Sevda.
