### ISSUE TITLE
Share template for the Project Milestone 1 Report

### ISSUE THREAD

**Issue by theTytoAlba** [bounswe/bounswe2017group7#117]
We are going to create a project report with LaTeX, where everybody will explain their part of the project.

I will create the template for people to fill in their parts.

Template will be shared on a branch where everybody will update that branch and when the report is ready, we will merge the branch to master.

**Comment by sevgicansalih** [comment]
If you could tell us how to fetch the common branch to our locals, it would be great, thank you for creating the template

**Comment by theTytoAlba** [comment]
Thanks for the tip, I will explain the details in the branch commit.

**Comment by theTytoAlba** [comment]
I have created the branch projectreport and pushed the template for the report.
