### ISSUE TITLE
Communication Tools (Everyone)

### ISSUE THREAD

**Issue by ebruzorlu** [bounswe/bounswe2017group7#12]
We should decide communication methods in the next meeting and create wiki page for our communication plan in tabular format.

**Comment by theTytoAlba** [comment]
I have added a wiki page for our communication plan but it is just a bullet-point list.

I can update the list but what should the table have as the columns? Name of the communication platform, when do we choose to use it, etc.?

**Comment by ebruzorlu** [comment]
columns can be type of communication, participants, frequency, audience

**Comment by theTytoAlba** [comment]
I have updated the communication plan and adopted our text-based decisions to the tabular form. Thanks for the draft! Looks like html is a life saver. 😄
