### ISSUE TITLE
Create Admin and Moderator types for admin panel

### ISSUE THREAD

**Issue by theTytoAlba** [bounswe/bounswe2017group7#129]
In the admin panel we have 2 types of users: Admins and Moderators.

Moderators won't be able to modify Conversation Tree nodes while admins can.

I will create the Moderator type for our admin panel.

**Comment by theTytoAlba** [comment]
Pull request sent

We have two types: AdminUser and ModeratorUser. See the access rights below.

<img width="1001" alt="screen shot 2017-11-20 at 14 40 24" src="https://user-images.githubusercontent.com/7192055/33017010-c190c188-ce01-11e7-9c31-50837aecd6f0.png">

<img width="990" alt="screen shot 2017-11-20 at 14 40 33" src="https://user-images.githubusercontent.com/7192055/33017028-cb60e6de-ce01-11e7-8937-17104629372d.png">

I can enter the admin site with a ModeratorUser account. (Details will be shared offline). See that moderators can only see what they are allowed. For example, they cannot add or remove comments but they can edit them (so they can flag them).
<img width="1255" alt="screen shot 2017-11-20 at 14 43 21" src="https://user-images.githubusercontent.com/7192055/33017034-d5806f36-ce01-11e7-8c9d-b0021edf094c.png">
<img width="1254" alt="screen shot 2017-11-20 at 14 43 29" src="https://user-images.githubusercontent.com/7192055/33017092-12b5f114-ce02-11e7-83c7-4b30a30754a4.png">

**Comment by sevgicansalih** [comment]
pull request is merged.
