### ISSUE TITLE
Create database model for books

### ISSUE THREAD

**Issue by theTytoAlba** [bounswe/bounswe2017group7#134]
Comments and rates need to be associated with books. For this, we need book objects.

**Comment by theTytoAlba** [comment]
The pull request is sent. Screenshots below.

Here you can see the book objects, they have isbn (necessary), and optionally they have title and author. If we need anything else we can add more fields later.
<img width="1280" alt="screen shot 2017-11-13 at 09 44 11" src="https://user-images.githubusercontent.com/7192055/32713176-1dd3368c-c859-11e7-861c-cb8cf36f4847.png">

Here you can see we can select a book for a comment.
<img width="1239" alt="screen shot 2017-11-13 at 09 50 54" src="https://user-images.githubusercontent.com/7192055/32713151-f7cd74de-c858-11e7-8669-30f5c52b1caa.png">

Here you can see we can filter comments by users or books.
<img width="1263" alt="screen shot 2017-11-13 at 09 53 12" src="https://user-images.githubusercontent.com/7192055/32713141-e7c1dc2e-c858-11e7-8254-1884eab93580.png">

**Comment by sevgicansalih** [comment]
I've reviewed your code. Well done.

**Comment by theTytoAlba** [comment]
This change was merged. Closing.
