### ISSUE TITLE
Fix the older issue names and add labels (Everyone)

### ISSUE THREAD

**Issue by theTytoAlba** [bounswe/bounswe2017group7#14]
As we have discussed in the lecture, having identical names for issues is not a good practice, but we did make this mistake. Let's _fix_ this!

Luckily we can edit older/closed issues. So please;

1. Go to your closed issue about creating a personal page.
1. Edit the issue name, add your name in the title so that it is different and explanatory.
1. Edit the issue body and add some explanation about the issue (we dont want any empty issue bodies).
1. Add the **LABEL** i just created (that is the yellow _new wiki page_ label)
1. Come and comment here so we know that your part is done and we can close this issue when everyone is done. :)

**Comment by ahmetcihat** [comment]
I just edited two of the closed issues.

**Comment by fatihmehmetkiris** [comment]
done 👍

**Comment by agoz17** [comment]
Done!

**Comment by seckintayfun** [comment]
Done.

**Comment by sevgicansalih** [comment]
# DONE

**Comment by theTytoAlba** [comment]
Looking niiice, thanks everybody!
