### ISSUE TITLE
Update Gannt Chart

### ISSUE THREAD

**Issue by sevgicansalih** [bounswe/bounswe2017group7#145]
We need to update our Gannt chart of our project plan for convenience.
We could use this website to do this : http://www.ganttproject.biz/

**Comment by agoz17** [comment]
I found a possibly useful gantt chart tool in this link :  https://prod.teamgantt.com I'm going to transfer our plan as much as I can do. I can share the plan with anyone wants to contribute.

**Comment by agoz17** [comment]
I have transferred our plan and made some changes on it. We can discuss the changes on the meeting tomorrow. The new tool letting us to change our plan quickly and easy.
