### ISSUE TITLE
TA Meeting

### ISSUE THREAD

**Issue by agoz17** [bounswe/bounswe2017group7#15]
We need some info about how should we proceed in terms of frameworks we should use for the project. We need all contribute to these questions. These are some questions that we might want to ask.

1-In our project do we need to implement only a chat environment or do we need to implement other page structures as well?

2- Are we going to implement a profile and sharing infrastructure for this project?

3-If it should have a chatbot with a conversation environment and at the same time we are going to let users have profiles and share things about books how are we going to relate these two things since their main point of existence is completely different?

4- What exactly wants the customer?

**Comment by theTytoAlba** [comment]
TA meeting is scheduled on 20th of february, 12:30. We will ask these questions.

**Comment by sevgicansalih** [comment]
Wiki page of meeting notes with TA has been created.
