### ISSUE TITLE
Creating Issues and  the Steps we should take

### ISSUE THREAD

**Issue by agoz17** [bounswe/bounswe2017group7#170]
Hi all,

I think we need to specify some extra small/divided implementation parts to finish for our ChatBot project in addition to what we have. Handling these minimum requirements would suffice to reach MVP of our product. And if we can divide these things equally there won't be too much work per person. We can discuss this issue under this thread. After a short discussion, we can create the necessary issues on git and corresponding work sharing. Then get to working.

My recommendations are:

1-
Firstly considering these requirements:
**1.2.1.1.1.1.1. User should be able to search books by given name.
1.2.1.1.1.1.2. User should be able to search books by specified genre.
1.2.1.1.1.1.3. User should be able to search books by specified author.**

Implementation of goodreads side of the bot could be divided to fulfill these 3 requirements. It can be divided to two person who wants to solve these. We are finding genre now but, it is not working bug free for now. It would take only 20-25 lines of code to develop each function. The only thing I want us to consider is to test this function very closely since it is buggy already.

We also need to develop the db side of this feature. It should look first our db.

2-
**1.2.1.1.2.1. User shall be able to see the comments on a book.
1.2.1.1.2.2. User shall be able to see the ratings on a book.**

Getting comments and getting average ratings of a book in the database is critical. We need to do these. However, there is not much work to do here. One person can do it I think.

3-
**1.2.1.3 User shall be able to get book recommendations.**

This one is also critical I think. About this I said that I can handle it, however a little help would make it better. We are going to implement a basic collaborative filtering algorithm for this purpose. I'm going to commit implementation of similarity calculations this saturday morning. However for the rest of the job, I need one or two more person who want to contribute.

4-
Preparation for the Final Milestone
We need to consider creating demo scenario and plan for the final demo. In this task, we need these things:
-creating a dialog scenario
-training wit for the nodes in the dialog 
-making sure that dialog is working
-preparing the powerpoint presentation
-preparing the report about the milestone 

This one can be handled by two person at least.

For the tasks we need 7-8 working people. We can divide it  accordingly to the willing persons.

If any one wants to add more issues to this thread or anywhere it is okay for me. And if you have whole another different ideas and way of planning, I can work with that also. I wanted to just hold everything we need to do in one place and discuss it if needed. And also I wanted to minimize our work and share it between us. I think this is the only way we can conclude this project without failing considering other courses and projects we have. I'm waiting for inputs from the people who wants to do least and get the most.

**Comment by tahakucukkatirci** [comment]
I implemented Part 2. We need to test it before presentation and fix the bugs if there are any.

**Comment by tahakucukkatirci** [comment]
I implemented Part 1. We need to test it before presentation and fix the bugs if there are any.

**Comment by agoz17** [comment]
We have done all the parts with taking good amount of responsibilities each. Thanks to you @tahakucukkatirci  @melihmutlu @sevgicansalih  @theTytoAlba .
