### ISSUE TITLE
Unicode character problem

### ISSUE THREAD

**Issue by tahakucukkatirci** [bounswe/bounswe2017group7#179]
We might need to handle unicode characters in the response we get from Goodreads API.

**Comment by sevgicansalih** [comment]
That has been already handled in telegrambot.py file by replacing some special characters with others. If you have any other problems please give an example

In telegrambot.py, under the definition of send_message 
`if(isinstance(message,list)):`
&emsp;`for index in message:`
&emsp;&emsp;`sendURL = URL + "sendMessage?text={}&chat_id={}".format(index, chat_id);`
&emsp;&emsp;`sendURL = sendURL.replace("#","No:")`
&emsp;&emsp;`send_request(sendURL);`
&emsp;&emsp;`time.sleep(0.3);`

For further handling of unicode characters, you can make some additions in here.

**Comment by sevgicansalih** [comment]
For unhandled utf-8 special char problems I've found and tested this solution, it is working for any string.
`import re`
`text = re.sub('[^A-Za-z0-9]+', ' ', text)
`

**Comment by tahakucukkatirci** [comment]
It seems like there is nothing to worry about unicode characters on Telegram chat. Closing the issue
