### ISSUE TITLE
Adding admin requirements and finalizing the project requirements page (Everyone)

### ISSUE THREAD

**Issue by ahmetcihat** [bounswe/bounswe2017group7#20]
Because that we need a template system for the bot to recognize the user's input, there is going to be an extra service where admins can add templates and all other stuff. In this assignment we will clearly specify the requirements. And there is going to be visual change on the requirements page. This assignment will be done until 28 February.

**Comment by sevgicansalih** [comment]
While creating use case scenerios page, some missing requirements are detected. In the upcoming days , Project requirements page will be updated.

**Comment by theTytoAlba** [comment]
Requirements are updated:

* User requirements are up-to-date.
* Admin requirements are up-to-date.
* Moderator requirements are up-to-date.
* System requirements are mostly up-to-date but are still growing as the class diagram evolves.

 Closing this issue, system requirements will be finalized after the class diagram feedbacks are applied and class diagram is finalized.
