### ISSUE TITLE
Update Telegram Mockup

### ISSUE THREAD

**Issue by ebruzorlu** [bounswe/bounswe2017group7#23]
Update telegram mockups accoding to our TA's advices

**Comment by theTytoAlba** [comment]
Conversation is longer ✔️ 
Screen recorded so that we can see what will happen in real time ✔️ 
I am going to accelerate the video a bit and then upload. (Maybe we shold convert it into a gif?)

**Comment by theTytoAlba** [comment]
This is what we have up to now.

![ezgif com-optimize](https://cloud.githubusercontent.com/assets/7192055/23611149/78a69564-027e-11e7-92fa-8a6fd9d232bc.gif)

**Comment by ebruzorlu** [comment]
I have just added conservation samples for bot.

**Comment by ebruzorlu** [comment]
We finished editing telegram mockup and creating conservation samples.
