### ISSUE TITLE
Add new use case scenerios

### ISSUE THREAD

**Issue by theTytoAlba** [bounswe/bounswe2017group7#28]
We currently have one use case scenerio; you can find it [here](https://github.com/bounswe/bounswe2017group7/wiki/Use-Case-Scenerios).

We need to add new scenerios. My propositions are;
*  A scenerio where Leonardo (or any user you want^^) searches a book and gets feedback on that book. We need to show that our bot is capable of showing *comments* and *ratings*.  
* A scenerio where Leonardo wants to give feedback after reading a book. He should *rate* and *comment* on the book.
*  A scenerio where Leonardo meets some of the admins and wants to contribute to the bot. Admins can give him an invitation code and he might sign up to the admin page.

Feel free to add any scenerio where we can tell a story of our bot's capabilities.  
And feel free to assign yourself!

**Comment by theTytoAlba** [comment]
Added a new scenerio about Lisa using the feedback features of the Book Bot.

**Comment by ahmetcihat** [comment]
I've just added two more scenarios and changed the template. If the TA approves it, the issue will be closed.

**Comment by ahmetcihat** [comment]
All the scenarios are finalized.
