### ISSUE TITLE
Design Sequence Diagrams 

### ISSUE THREAD

**Issue by melihmutlu** [bounswe/bounswe2017group7#29]
Sequence Diagrams need to be done.
All diagrams should reflect elements that are specifically related to the project

**Comment by theTytoAlba** [comment]
Class Diagram and Sequence Diagram are seperate topics, therefore they should have seperate issues. Can you please change this issue to Sequence Diagram so that Salih and I can open another issue for the Class diagram?

**Comment by theTytoAlba** [comment]
Thank you, I am unassigning Salih and me and opening a new issue for the class diagram. :)
