### ISSUE TITLE
Design Class Diagram

### ISSUE THREAD

**Issue by theTytoAlba** [bounswe/bounswe2017group7#30]
We need to design the class diagram for our project.

**Comment by theTytoAlba** [comment]
Diagram is designed on paper and currently being drawn on pc.

**Comment by sevgicansalih** [comment]
![classdiagram](https://cloud.githubusercontent.com/assets/19365781/23875854/93d3c0c6-0843-11e7-97db-b382acd06820.png)
Current Desing of Class Diagram is ready.
There can be also further updates through a new issue.
