### ISSUE TITLE
Setting up Amazon Server

### ISSUE THREAD

**Issue by ismetkoralay** [bounswe/bounswe2017group7#77]
We will set up amazon service and account.

**Comment by theTytoAlba** [comment]
I remember you had some progress about this issue, can you post the updates here please?

**Comment by agoz17** [comment]
Ismet and Akin, do you need help on this issue? Maybe we can add some people on this issue if you need, to make progress faster.

**Comment by ismetkoralay** [comment]
We have a working instance now. I'm going to try to install django on the server.

**Comment by akinarpacioglu** [comment]
We set up the amazon server.
