### ISSUE TITLE
Book API implementation

### ISSUE THREAD

**Issue by sevgicansalih** [bounswe/bounswe2017group7#89]
Google Books api, or Good Reads api will be implemented to our django module.

**Comment by sevgicansalih** [comment]
GoodReads API interface has been added, I've used [this](https://github.com/sefakilic/goodreads) repo. On the [bookapi branch](https://github.com/bounswe/bounswe2017group7/tree/bookapi) you can see the changes and common_room.py to implement methods where all the libraries can be used. 
When the methods related to GoodReads api, this issue will be closed

**Comment by sevgicansalih** [comment]
Pull Request created. instead of common_room.py file is changed to goodreadsApi.py in order to exhibit an example of api usage

**Comment by theTytoAlba** [comment]
A note for the future issues: Let's close the issue after we merge the branch. 😄
